version : '3'
services :
  server1 :
    build:
      context: .
      dockerfile: Dockerfile.server
    ports :
      - "5001:5000"
  server2 :
    build: 
      context: .
      dockerfile: Dockerfile.server
    ports :
      - "5002:5000"
  server3 :
    build: 
      context: .
      dockerfile: Dockerfile.server
    ports :
      - "5003:5000"

  client :
    build: 
      context: .
      dockerfile: Dockerfile.client
    ports :
      - "5000:5000"

  web:
    image: "nginx"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports :
      - "8095:8090"
    command: [nginx-debug, '-g', 'daemon off;']
    